---
# Configure system 
#
- hosts: localhost
  become: true
  tasks:

    - name: upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: Enable RPM Fusion
      dnf:      
        name:
          - "http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.noarch.rpm"
          - "http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.noarch.rpm"

    - name: Install Fedy
      shell: |
        dnf -y copr enable kwizart/fedy
        dnf -y install fedy       
      args:
        creates: "/usr/bin/fedy"

    - name: 
      shell: |
         dnf -y install  dnf-automatic
         systemctl enable dnf-automatic-download.timer
         systemctl start dnf-automatic-download.timer

    - name: Install essentials
      dnf: 
        name:
          - htop
          - vim 
          - ack
          - ShellCheck
        state: latest 

    - name: Install some backgrounds
      dnf:
        name:
          - f30-backgrounds-extras-gnome
          - f31-backgrounds-extras-gnome 
          - f32-backgrounds-extras-gnome 

    - name: Install Slack
      dnf: 
        name: "https://downloads.slack-edge.com/linux_releases/slack-4.2.0-0.1.fc21.x86_64.rpm"
    
    - name: Install vs-code
      shell: |
        rpm --import https://packages.microsoft.com/keys/microsoft.asc
        sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
        dnf check-update
        dnf -y install code
      args:
        creates: "/usr/bin/code"

    - name: Install go
      dnf:
        name: go
        state: latest

    - name: Install container tools
      dnf:
        name:
          - podman
          - buildah
          - skopeo
          - toolbox

    - name: Redundantly check ansible install 
      dnf:
        name:
          - ansible
          - ansible-lint


    - name: Install virtualization stuff
      shell: |
        dnf -y group install --with-optional virtualization
        systemctl start libvirtd
        systemctl enable libvirtd

      # Might want to add check for kvm_amd module 
      # lsmod | grep kvm

    - name: Install multimedia stuff
      shell: |
        dnf -y install  gstreamer1-plugins-{bad-\*,good-\*,base} gstreamer1-plugin-openh264 gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel
        dnf -y install -y  lame\* --exclude=lame-devel
        dnf -y group upgrade --with-optional Multimedia

    - name: Install VLC
      dnf:
        name: vlc

    - name: Install Gnome Shell Extension Stuff
      dnf: 
        name: 
          - gnome-shell-extension-dash-to-dock
          - gnome-shell-extension-appindicator      
          - gnome-extensions-app

    - name: Install Gnome Tweak Tool        
      dnf:
        name: 
          - gnome-tweaks


# Configure userland 
#
- hosts: localhost
  tasks:
    - name: Configure frame-flash visual bell 
      shell: |
        gsettings set org.gnome.desktop.wm.preferences audible-bell false
        gsettings set org.gnome.desktop.wm.preferences visual-bell true
        gsettings set org.gnome.desktop.wm.preferences visual-bell-type frame-flash

    - name: Install pipx
      pip: 
        name: pipx
        extra_args: --user

    - name: Install some Python apps with pipx
      shell: |
        pipx install black  
        pipx install yamllint
